# Based on: https://github.com/mapbox/node-pre-gyp/blob/master/appveyor.yml

os: Visual Studio 2015

environment:
  matrix:
    - nodejs_version: '12'
      platform: x64
      msvs_toolset: 12
    - nodejs_version: '10'
      platform: x64
      msvs_toolset: 12
    - nodejs_version: '8'
      platform: x64
      msvs_toolset: 12

  npm_config_arch: x64

platform: x64

shallow_clone: true

configuration: Release

skip_commits:
  files:
    - docs/*
    - Dockerfile
    - travis.yml
    - '**/*.html'
    - '*.md'

init:
  - cmd: node --version
  - cmd: npm --version

install:
  - ps: Install-Product node $env:nodejs_version $env:Platform
  - ps: Set-ExecutionPolicy Unrestricted -Scope CurrentUser -Force
  - ps: npm set audit false

  # Install gnats
  - appveyor DownloadFile https://github.com/nats-io/gnatsd/releases/download/v1.4.1/gnatsd-v1.4.1-windows-386.zip
  - 7z e gnatsd-v1.4.1-windows-386.zip gnatsd.exe -r -oc:\projects\hemera\build
  - cmd: set PATH=%PATH%;C:\projects\hemera\build

  - yarn install
  - yarn run test

build: off
test: off
deploy: off
