language: node_js
sudo: true

node_js:
  - "4"
  - "6"
  - "7"
  - "8"

script:
  - npm run ci:setup && npm run ci

env:
  - CXX="g++-4.8"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - gcc-4.8

before_script:
  # install nats
  - wget https://github.com/nats-io/gnatsd/releases/download/v1.0.2/gnatsd-v1.0.2-linux-amd64.zip -qO tmp.zip
  - unzip tmp.zip
  - mv gnatsd-v1.0.2-linux-amd64 gnatsd

notifications:
  email:
    on_success: never
    on_failure: always
