language: node_js
sudo: true

node_js:
  - "4"
  - "7"
  - "8"

script:
  - npm run setup && npm run ci

env:
  - CXX="g++-4.8"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - gcc-4.8

before_script:
  # install nats
  - wget https://github.com/nats-io/gnatsd/releases/download/v0.9.6/gnatsd-v0.9.6-linux-amd64.zip -qO tmp.zip
  - unzip tmp.zip
  - mv gnatsd-v0.9.6-linux-amd64 gnatsd

notifications:
  email:
    on_success: never
    on_failure: always
