language: node_js

node_js:
  - '10'
  - '8'
  - '6'

script:
  - npm set audit false
  - npm run ci:setup && npm run ci

before_script:
  # install nats
  - wget https://github.com/nats-io/gnatsd/releases/download/v1.0.4/gnatsd-v1.0.4-linux-amd64.zip -qO tmp.zip
  - unzip tmp.zip
  - mv gnatsd-v1.0.4-linux-amd64 gnatsd

notifications:
  email:
    on_success: never
    on_failure: always
